
{RIL_SAMSUNG_REQUEST_DIAL_EMERGENCY_CALL               , dispatchDial      , responseVoid},
{RIL_SAMSUNG_REQUEST_CALL_DEFLECTION                   , dispatchString    , responseVoid},
{RIL_SAMSUNG_REQUEST_MODIFY_CALL_INITIATE              , dispatchCallModify, responseInts},
{RIL_SAMSUNG_REQUEST_MODIFY_CALL_CONFIRM               , dispatchCallModify, responseVoid},
{RIL_SAMSUNG_REQUEST_SET_VOICE_DOMAIN_PREF             , dispatchInts      , responseVoid},
{RIL_SAMSUNG_REQUEST_SAFE_MODE                         , dispatchInts      , responseVoid},
{RIL_SAMSUNG_REQUEST_SET_TRANSMIT_POWER                , dispatchInts      , responseVoid},
{RIL_SAMSUNG_REQUEST_GET_CELL_BROADCAST_CONFIG         , dispatchVoid      , responseCBConfig},
{RIL_SAMSUNG_REQUEST_GET_PHONEBOOK_STORAGE_INFO        , dispatchInts      , responseInts},
{RIL_SAMSUNG_REQUEST_GET_PHONEBOOK_ENTRY               , dispatchSIM_IO    , responsePBE},
{RIL_SAMSUNG_REQUEST_ACCESS_PHONEBOOK_ENTRY            , dispatchPhoneEntry, responseInts},
{RIL_SAMSUNG_REQUEST_USIM_PB_CAPA                      , dispatchVoid      , responseInts},
{RIL_SAMSUNG_REQUEST_LOCK_INFO                         , dispatchLockInfo  , responseLockInfo},
{RIL_SAMSUNG_REQUEST_STK_SIM_INIT_EVENT                , dispatchVoid      , responseVoid},
{RIL_SAMSUNG_REQUEST_SET_PREFERRED_NETWORK_LIST        , dispatchPreferredNetwork, responseVoid},
{RIL_SAMSUNG_REQUEST_GET_PREFERRED_NETWORK_LIST        , dispatchVoid      , responsePreferredNetworkList},
{RIL_SAMSUNG_REQUEST_CHANGE_SIM_PERSO                  , dispatchStrings   , responseInts},
{RIL_SAMSUNG_REQUEST_ENTER_SIM_PERSO                   , dispatchStrings   , responseInts},
{RIL_SAMSUNG_REQUEST_SEND_ENCODED_USSD                 , dispatchEncodedUSSD, responseVoid},
{RIL_SAMSUNG_REQUEST_CDMA_SEND_SMS_EXPECT_MORE         , dispatchCdmaSms   , responseSMS},
{RIL_SAMSUNG_REQUEST_HANGUP_VT                         , dispatchInts      , responseVoid},
{RIL_SAMSUNG_REQUEST_HOLD                              , dispatchVoid      , responseVoid},
{RIL_SAMSUNG_REQUEST_SET_SIM_POWER                     , dispatchInts      , responseInts},
{RIL_SAMSUNG_REQUEST_SET_LTE_BAND_MODE                 , dispatchInts      , responseVoid},
//{UICC_GBA_AUTHENTICATE_BOOTSTRAP   , },
{ 0, NULL, NULL },
//{UICC_GBA_AUTHENTICATE_NAF         , },
{ 0, NULL, NULL },
{RIL_SAMSUNG_REQUEST_GET_INCOMING_COMMUNICATION_BARRING, dispatchStrings   , responseString},
{RIL_SAMSUNG_REQUEST_SET_INCOMING_COMMUNICATION_BARRING, dispatchStrings   , responseInts},
